services:
  - docker

before_install:
  - docker build -t hazartilirot/react -f Dockerfile.dev .

script:
  - docker run -e CI=true hazartilirot/react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: eu-central-1
  app: travis
  env: Travis-env
  bucket_name: elasticbeanstalk-eu-central-1-035766875271
  bucket_path: travis
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY